### ISSUE TITLE
Exit Zero, add -dit, bash & all to docker-compose.yml

### ISSUE THREAD

**Issue by TurtleWolf** [TurtleWolf/docker-run--it-ubuntu-latest-bin-bash#1]
### $`docker attach u1804`  
Running these 2 commands will get me into the prompt of a Linux system, which is really all I need for now.  Most of my time has been on Windows or Mac.. so I really just want a Local Linux to review from first principles. 
### root@u1804:/# `exit`  
It's been much easier to find tutorials about running Docker on Linux rather than Linux in Docker..  
_Now,_ I'm trying to move that functionality into __docker-compose.yml__ so with just `compose-docker up` brings me back to that same Linux prompt. I'm getting as far as an exit zero, it looks like it's pulling the image and building the container, but then it exits with a zero because it's finished.. I'm not sure about the syntax to add  
1. `-detached`
1.  `-interactive`
1. `-TTY` and the
1. `//bash` call?  
Also, instead of just adding the `usr/local/`, could I expose the entire file structure of `18.04` to local development?  
### docker-compose.yml
```
version: "3.2"
services:
  bionic:
    image: ubuntu:${DISTRO:-bionic}
    ports:
      - "8080:80"
    volumes:
      - ./usr_local/:/usr/local/
    container_name: u1804
```
